defaults:
    - base.yaml

experiment:
    name: "deal_no_deal"
    method: generate_and_train
    description: "Deal-or-No-Deal negotiation game"
    nb_epochs: 1000
    nb_matches_per_iteration: 32
    reinit_matches_each_it: true
    checkpoint_every_n_iterations: 25
    start_epoch: 0
    resume_experiment: true
    base_seed: 1001


markov_games:
    simulation_class_name: DealNoDealSimulation
    simulation_init_args:
        agent_ids: ${agent_ids}
        rounds_per_game: 10
        quota_messages_per_agent_per_round: 1
        item_types: ["books", "hats", "balls"]

    agents:
        0:
            agent_id: ${agent_0_id}
            agent_class_name: DealNoDealAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs

        1:
            agent_id: ${agent_1_id}
            agent_class_name: DealNoDealAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs
