# To quickly check if code still runs
experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"

defaults:
    - tas_rps_ad_align.yaml

models:
    base_llm:
        init_args:
            model_name: Qwen/Qwen3-8B
            enable_thinking: False
            regex_max_atstempts: 3
            inference_backend_init_kwargs:
                enforce_eager: False
                gpu_memory_utilization: 0.99
                max_loras: ${lora_count}
                max_cpu_loras : ${lora_count}
                enable_sleep_mode: True
                enable_lora: True
