# To quickly check if code still runs
experiment:
    name: "debug_nego_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 20
    nb_matches_per_iteration: 16
    train: true

defaults:
    - no_press_10_1_ties_ad_align_hc_buffers.yaml


markov_games:

    simulation_init_args:
        nb_of_rounds: 1

    hard_coded_buffer_agents:
        0:
            agent_id: AutoGreedy
            agent_class_name: HardCodedNegoGreedyPolicy

        1:
            agent_id: AutoCooperative
            agent_class_name: HardCodedNegoWelfareMaximizingPolicy



models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            llm_id: base_llm
            enable_thinking: False
            model_name: "Qwen/Qwen3-4B-Instruct-2507" # Qwen/Qwen3-4B-Instruct-2507
            inference_backend: vllm



trainers:
    agent_trainer:
        kwargs:
            enable_tokenwise_logging: True
            
