# To quickly check if code still runs

defaults:
    - ipd.yaml

experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 1000
    nb_matches_per_iteration: 64
    reinit_matches_each_it: true
    checkpoint_every_n_iterations: 1e5
    start_epoch: 0
    resume_experiment: true
    base_seed: 1000
    train: false

agent_0_id: Alice
agent_1_id: Bob
agent_ids: ["Alice", "Bob"]

markov_games:
    simulation_init_args:
        rounds_per_game: 4


temperature: 1.0

models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            llm_id: base_llm
            model_name: "Qwen/Qwen2.5-0.5B-Instruct" # Qwen/Qwen3-4B-Instruct-2507
            inference_backend: dummy
            reward_normalizing_constant: 5.0
