# To quickly check if code still runs

defaults:
    - tas.yaml

experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 2
    nb_matches_per_iteration: 8
    seed_group_size: 2


markov_games:
    runner_method_name: LinearRunner
    runner_kwargs: {}
    simulation_class_name: TrustAndSplitSimulation
    simulation_init_args:
        rounds_per_game: 10
models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            llm_id: base_llm
            model_name: "Qwen/Qwen3-4B-Instruct-2507" # Qwen/Qwen3-4B-Instruct-2507
            inference_backend: dummy
trainers:
    agent_trainer:
        class: TrainerSumRewards
        kwargs:
            enable_tokenwise_logging: True
