# To quickly check if code still runs
experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"

defaults:
    - tas_rps_ad_align.yaml

optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 1e-2
            weight_decay: 0.0

    critic_optimizer:
        module_pointer: agent_critic
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0

trainers:
    agent_trainer:
        kwargs:
            kl_coeff: 1e5
            enable_tokenwise_logging: True
