# To quickly check if code still runs

defaults:
    - ipd_prev_ad_align.yaml
experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"
    nb_matches_per_iteration: 12



optimizers:
    agent_optimizer:
        init_args:
            lr: 3e-6
            weight_decay: 0.0

markov_games:
    simulation_init_args:
        rounds_per_game: 4

models:
    base_llm:
        init_args:
            model_name:  Qwen/Qwen3-4B-Instruct-2507 # Qwen/Qwen3-4B-Instruct-2507, Qwen/Qwen2.5-7B-Instruct

trainers:
    agent_trainer:
        kwargs:
            use_whitening: True
            ad_align_beta: 1.0
            reward_normalizing_constant: 1.0
            skip_discounted_state_visitation: False
            ad_align_gamma: 1.0
            ad_align_only_use_main_advantages: True
            use_rloo: True
