defaults:
    - no_press_10_1_ties_ad_align_hc_buffers.yaml


# To quickly check if code still runs
experiment:
    name: "debug_nego_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 20
    nb_matches_per_iteration: 4
    seed_group_size: 1
    train: true


models:
    base_llm:
        init_args:
            llm_id: base_llm
            enable_thinking: False
            model_name: "Qwen/Qwen3-4B-Instruct-2507" # Qwen/Qwen3-4B-Instruct-2507
            inference_backend: vllm

simulation_init_args:
    nb_of_rounds: 1
