# To quickly check if code still runs
experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"

defaults:
    - no_press_naive.yaml

optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 1e-4
            weight_decay: 0.0
