# To quickly check if code still runs

defaults:
    - ipd_ad_align.yaml


experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 10
    nb_matches_per_iteration: 2
    reinit_matches_each_it: true
    checkpoint_every_n_iterations: 1e5
    start_epoch: 0
    resume_experiment: true
    base_seed: 1000


agent_0_id: Alice
agent_1_id: Bob
agent_ids: ["Alice", "Bob"]

markov_games:
    simulation_init_args:
        rounds_per_game: 3


temperature: 1.0

models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            model_name: Qwen/Qwen2.5-0.5B-Instruct
