defaults:
    - tas_rps_naive_gemma-3-4b-it.yaml


# To quickly check if code still runs
experiment:
    name: "debug_nego_${now:%Y-%m-%d___%H-%M-%S}"
    nb_epochs: 20
    nb_matches_per_iteration: 4
    seed_group_size: 1
    train: true

models:
    base_llm:
        init_args:
            regex_max_attempts: -1
            inference_backend: vllm
            inference_backend_init_kwargs:
                enforce_eager: True

markov_games:
    simulation_init_args:
        nb_of_rounds: 2
