# To quickly check if code still runs

defaults:
    - negotiation_game.yaml

experiment:
    name: "debug_${now:%Y-%m-%d___%H-%M-%S}"

matches:
    max_length: 2
    continuation_prob: 1.0

common_agent_kwargs: &common_agent_kwargs
    allow_reasoning: True
    max_reasoning_chars: 200
