hydra:
  run:
    dir: "/home/mila/d/dereck.piche/llm_negotiation/outputs/${now:%Y-%m-%d___%H-%M-%S}___${experiment.name}"
  job:
    chdir: false

experiment:
  name: "diplomacy_dummy_test"
  method: generate_and_train
  description: "diplomacy_dummy_test"
  nb_epochs: 500
  nb_matches_per_iteration: 32
  reinit_matches_each_it: true
  start_epoch: 0
  resume_experiment: true
  base_seed: 42

training:
  keep_error_messages: False
  llama:
    adapters:
      # Define an adapter for each of the 7 powers in Diplomacy
      ad_austria:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_england:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_france:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_germany:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_italy:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_russia:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0
          
      ad_turkey:
        train_func: train_reinforce_main
        train_func_args:
          temperature: 1
          learning_rate: 1e-6
          entropy_coef: 0

models:
  llama:
    class: local_llm
    init_args: {}

  dummy:
    class: dummy_local_llm
    init_args:
      name: 'dummy'
      adapter_names: ['ad_austria', 'ad_england', 'ad_france', 'ad_germany', 'ad_italy', 'ad_russia', 'ad_turkey']



matches:
  env_class: "DiplomacyEnv"
  env_kwargs:
    map_name: "standard"
    game_id: "test"
    rules: "standard"

  log_func: "diplomacy_log_match"
  log_func_args: {}
  
  agent_class: "DiplomacyAgent"

  agents:
    AUSTRIA:
      kwargs:
        policy_id: "dummy/ad_austria"
        power_name: "AUSTRIA"
        random_valid_move: true

    ENGLAND:
      kwargs:
        policy_id: "dummy/ad_england"
        power_name: "ENGLAND"
        random_valid_move: true

    FRANCE:
      kwargs:
        policy_id: "dummy/ad_france"
        power_name: "FRANCE"
        random_valid_move: true
      
    GERMANY:
      kwargs:
        policy_id: "dummy/ad_germany"
        power_name: "GERMANY"
        random_valid_move: true

    ITALY:
      kwargs:
        policy_id: "dummy/ad_italy"
        power_name: "ITALY"
        random_valid_move: true

    RUSSIA:
      kwargs:
        policy_id: "dummy/ad_russia"
        power_name: "RUSSIA"
        random_valid_move: true

    TURKEY:
      kwargs:
        policy_id: "dummy/ad_turkey"
        power_name: "TURKEY"
        random_valid_move: true

  run_batched_matches_args: 
    nb_parallel_matches: -1
