hydra:
    run:
        dir: "${oc.env:SCRATCH}/llm_negotiation/${now:%Y_%m}/${experiment.name}"

    job:
        chdir: false

experiment:
    name: "ipd"
    method: generate_and_train
    description: "no description"
    nb_epochs: 1000
    nb_matches_per_iteration: 64
    reinit_matches_each_it: true
    checkpoint_every_n_iterations: 50
    start_epoch: 0
    resume_experiment: true
    base_seed: 1000

####################################################################################################
#                                           GENERATION
####################################################################################################

common_agent_kwargs: &common_agent_kwargs
    max_errors: 0
    allow_reasoning: false
    max_reasoning_chars: 0
    cooperate_string: <A>
    defect_string: <B>
    strategy_prompt: ""
    intro_prompt: |
        Welcome to an iterated game. You are playing against another agent.

        Game Rules:
        1. In each round, both agents simultaneously choose to either play A or B.
        2. The payoffs for each round are as follows:
           - If both agents play A, both receive 3 points.
           - If both agents play B, both receive 1 points.
           - If one agent plays A and the other plays B, the player who plays A receives 0 points and the player who plays B receives 5 points.
        3. The goal is to maximize your total points over all rounds.
        4. You will see the previous play of the other player after the completion of a round.

        In order to play A, you must write "<A>" and nothing else.
        In order to play B, you must write "<B>" and nothing else.

        During the entire game, you must only write "<A>" or "<B>". If you write anything else, your response will be considered as an error.

        The game starts now:

    goal_prompt: |
        Your goal is to maximize your utility.

agent_0_id: Alice
agent_1_id: Bob
agent_ids: ["Alice", "Bob"]

markov_games:
    runner_method_name: LinearRunner
    runner_kwargs: {}
    simulation_class_name: IPD
    simulation_init_args:
        rounds_per_game: 10
        cooperate_actions: ["<A>"]
        defect_actions: ["<B>"]
        agent_ids: ${agent_ids}
        reward: 3
        punishment: 1
        temptation: 5
        sucker: 0
    agents:
        0:
            agent_id: ${agent_0_id}
            agent_class_name: IPDAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs

        1:
            agent_id: ${agent_1_id}
            agent_class_name: IPDAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs

    log_func: log_ipd_match

    run_batched_matches_args:
        nb_parallel_matches: -1

temperature: 1.0

models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            llm_id: base_llm
            model_name: Qwen/Qwen3-4B-Instruct-2507
            inference_backend: vllm
            hf_kwargs:
                device_map: "auto"
                torch_dtype: "bfloat16"
                max_memory: {0: "15GiB"}
                attn_implementation: "flash_attention_2"
            inference_backend_init_kwargs:
                max_model_len: 1e4
                # max_num_seqs: 64 # the max number of sequences that can be generated in parallel
                gpu_memory_utilization: 0.5
                dtype: "bfloat16"
                trust_remote_code: True
                max_lora_rank: 32
            inference_backend_sampling_params:
                temperature: 1.0
                top_p: 1.0
                max_tokens: 400
                top_k: 0
            adapter_configs:
                agent_adapter:
                    task_type: CAUSAL_LM
                    r: 32
                    lora_alpha: 64
                    lora_dropout: 0.0
                    target_modules: all-linear
                critic_adapter:
                    task_type: CAUSAL_LM
                    r: 32
                    lora_alpha: 64
                    lora_dropout: 0.0
                    target_modules: all-linear



critics:
    agent_critic:
        module_pointer: ["base_llm", "critic_adapter"]

optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 1e-6
            weight_decay: 0.0

    critic_optimizer:
        module_pointer: agent_critic
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 1e-6
            weight_decay: 0.0

trainers:
    agent_trainer:
        class: BaseTrainer
        module_pointers:
            policy: ["base_llm", "agent_adapter"]
            policy_optimizer: agent_optimizer
            critic: agent_critic
            critic_optimizer: critic_optimizer
        kwargs:
            entropy_coeff: 0.0
            kl_coeff: 0.0
            gradient_clipping: 1.0
            restrict_tokens: null
            mini_batch_size: 4
            use_gradient_checkpointing: True
            temperature: ${temperature}
            device: "cuda:0"
            use_gae: False
            skip_discounted_state_visitation: True
            gae_lambda_for_credits: 0.92
            gae_lambda_for_targets: 0.92
            discount_factor: 0.9
            use_rloo: True
            enable_tokenwise_logging: False
            pg_loss_normalization: "batch"
            reward_normalizing_constant: 5.0


train_on_which_data:
    agent_trainer: ${agent_ids} # take gradient steps on the reinforce data of both agents at once
