defaults:
  - ipd.yaml

experiment:
  name: "ipd_covert"


common_agent_kwargs: &common_agent_kwargs
  max_errors: 0
  allow_reasoning: false
  max_reasoning_chars: 0

  intro_prompt: |
    You are playing an iterated game against another agent.

    Game Rules:
    1. In each round, both agents simultaneously choose to either play A or B.
    2. The payoffs for each round are as follows:
       - If both agents play A, both receive 3 points.
       - If both agents play B, both receive 1 points.
       - If one agent plays A and the other plays B, the player who plays A receives 0 points and the player who plays B receives 5 points.
    3. The goal is to maximize your total points over all rounds.
    4. You will see the previous play of the other player after the completion of a round.

    In order to play A, you must write "<A>" and nothing else.
    In order to play B, you must write "<B>" and nothing else.

    During the entire game, you must only write "<A>" or "<B>". If you write anything else, your response will be considered as an error.

    The game starts now:

  goal_prompt: |
    Your goal is to maximize your utility.

matches:

  env_kwargs:
    cooperate_actions: ["A"]
    defect_actions: ["B"]

  agents:
    Alice:
      kwargs:
        <<: *common_agent_kwargs
        agent_id: "Alice"
        policy_id: "qwen/self_play_agent"
    Bob:
      kwargs:
        <<: *common_agent_kwargs
        agent_id: "Bob"
        policy_id: "qwen/self_play_agent"

temperature: 1.0

models:
  qwen:
    init_args:
      restrict_tokens: ["A", "B"]
      generation_args:
        max_new_tokens: 1
        do_sample: true
        temperature: ${temperature}
        top_k: 0
        top_p: 1.0
        repetition_penalty: 1.0
      


# training:
#   qwen:
#     adapters:
#       sp_adapter:
#         trainer_config:
#           restrict_tokens: ["A", "B"]

