defaults:
  - ipd.yaml

experiment:
    name: "ipd_faceoff_ad_align_itr100_greedy"
    description: "no description"
    nb_matches: 64
    base_seed: 1000



markov_games:
    agents:
        0:
            policy_id: base_llm/alice_adapter
        1:
            policy_id: base_llm/bob_adapter

models:
    base_llm:
        class: LeanLocalLLM
        init_args:
            model_name: Qwen/Qwen3-4B-Instruct-2507 # "Qwen/Qwen2.5-0.5B-Instruct" # Qwen/Qwen3-4B-Instruct-2507
            adapter_configs:
                alice_adapter:
                    task_type: CAUSAL_LM
                    r: 32
                    lora_alpha: 64
                    lora_dropout: 0.0
                    target_modules: all-linear
                bob_adapter:
                    task_type: CAUSAL_LM
                    r: 32
                    lora_alpha: 64
                    lora_dropout: 0.0
                    target_modules: all-linear
            initial_adapter_paths:
                alice_adapter: "/home/mila/m/mohammed.muqeeth/scratch/llm_negotiation/2025_08/ipd_ad_align/seed_1000/checkpoints/agent_adapter-iter_100-2025-08-13_15-52-50/agent_adapter"
                bob_adapter: "/home/mila/m/mohammed.muqeeth/scratch/llm_negotiation/2025_08/ipd/seed_1000/Qwen/Qwen3-4B-Instruct-2507/adapters/agent_adapter"
