defaults:
  - ipd_covert.yaml

experiment:
  name: "ipd_covert_adv_align_rloolater_temp1.0_fixedrounds30_gamma0.9_updatedreward_clipped"
  # name: "${now:%Y-%m-%d___%H-%M-%S}negotiation_game_adv_align"
  description: "Agents trained on negotiation game with advantage alignment."
  seed: 1045
  nb_epochs: 500

training:
  agents:
    Alice:
      training_data_func_args:
        score_method: rloo_advantage_alignment_scores
        score_method_kwargs:
          discount_factor: 0.9
          beta: 1.0
          time_decay: False
          regulate_var: False
    Bob:
      training_data_func_args:
        score_method: rloo_advantage_alignment_scores
        score_method_kwargs:
          discount_factor: 0.9
          beta: 1.0
          time_decay: False
          regulate_var: False
