defaults:
    - ipd.yaml

markov_games:
    runner_method_name: AlternativeActionsRunner
    runner_kwargs:
        nb_alternative_actions: 5
        max_depth: 10

trainers:
    agent_trainer:
        class: AdAlignTrainer
        kwargs:
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_gamma: 0.8
            ad_align_exclude_k_equals_t: False
            ad_align_use_sign: False
            ad_align_beta: 1.0
