defaults:
    - ipd.yaml

markov_games:
    runner_method_name: AlternativeActionsRunner


trainers:
    agent_trainer:
        class: AdAlignTrainer
        kwargs:
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_gamma: 1.0
            ad_align_exclude_k_equals_t: True
            ad_align_use_sign: False
            ad_align_beta: 1.0
