defaults:
  - ipd.yaml

experiment:
  name: "ipd_sum_of_rewards"
  # name: "${now:%Y-%m-%d___%H-%M-%S}_ipd_sum_of_rewards"
  description: "IPD with sum of rewards."

training:

  agents:
    Alice:
      training_data_func: ipd_generate_training_data_from_raw
      training_data_func_args:
        exclude_errors: False
        debug_output: True
        score_method: sum_rloo_scores
        score_method_kwargs:
          discount_factor: 1.0
    Bob:
      training_data_func: ipd_generate_training_data_from_raw
      training_data_func_args:
        exclude_errors: False
        debug_output: True
        score_method: sum_rloo_scores
        score_method_kwargs:
          discount_factor: 1.0
