defaults:
  - ipd_covert_stochastic_rounds.yaml

experiment:
  name: "ipd_covert_adv_align_temp1.0_clip_firstcoop_stochasticrounds"
  # name: "${now:%Y-%m-%d___%H-%M-%S}negotiation_game_adv_align"
  description: "Agents trained on negotiation game with advantage alignment."
  seed: 1045
  nb_epochs: 1000

training:
  agents:
    Alice:
      training_data_func_args:
        score_method: rloo_advantage_alignment_scores
        score_method_kwargs:
          discount_factor: 1.0
          beta: 1.0
          time_decay: False
          regulate_var: False
          clipping: True
          use_sign: False
          first_coop: True
          do_rloo_later: False
    Bob:
      training_data_func_args:
        score_method: rloo_advantage_alignment_scores
        score_method_kwargs:
          discount_factor: 1.0
          beta: 1.0
          time_decay: False
          regulate_var: False
          clipping: True
          use_sign: False
          first_coop: True
          do_rloo_later: False
