defaults:
    - ipd.yaml

experiment:
    name: "ipd_prev_ad_align_entropy_top_k_${now:%Y_%m_%d}"


trainers:
    agent_trainer:
        class: TrainerAdAlign
        kwargs:
            whiten_advantages_time_step_wise: True
            entropy_coeff: 1e4
            entropy_topk: 10
            ad_align_beta: 10
            ad_align_gamma: 0.9
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_exclude_k_equals_t: False
            ad_align_use_sign: False
            use_old_ad_align: True
            use_time_regularization: True
            use_rloo: True
            rloo_branch: False
            reuse_baseline: False
