defaults:
    - ipd.yaml

experiment:
    name: "ipd_old_ad_align"

markov_games:
    runner_method_name: AlternativeActionsRunner
    runner_kwargs:
        nb_alternative_actions: 1
        max_depth: 10

trainers:
    agent_trainer:
        class: TrainerAdAlign
        kwargs:
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_gamma: 0.9
            ad_align_exclude_k_equals_t: True
            ad_align_use_sign: False
            ad_align_beta: 0.1
            ad_align_only_use_main_advantages: True
