defaults:
    - ipd.yaml

experiment:
    name: "ipd_prev_ad_align"

models:
    base_llm:
        init_args:
            model_name:  Qwen/Qwen2.5-7B-Instruct # Qwen/Qwen2.5-7B-Instruct

trainers:
    agent_trainer:
        class: TrainerAdAlign
        kwargs:
            reward_normalizing_constant: 1.0
            ad_align_beta: 0.1
            ad_align_gamma: 0.9
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_exclude_k_equals_t: False
            ad_align_use_sign: False
            ad_align_only_use_main_advantages: True
            use_time_regularization: False
            use_rloo: True
            rloo_branch: False
            reuse_baseline: False
