defaults:
  - negotiation_game.yaml

experiment:
  name: "negotiation_game_adv_align_temp1.0_sign_firstcoop"
  description: "Agents trained on negotiation game with advantage alignment."
  seed: 1045
  nb_epochs: 500

matches:
  nb_matches_with_same_roundwise_utilities: 64


training:
  qwen:
    adapters:
      sp_adapter:
        trainer_config:
          discount_factor: 1.0
          use_advantage_alignment: True
          ad_align_force_coop_first_step: True
          use_sign_in_ad_align: True
          ad_align_clipping: None
          use_time_regularization_in_ad_align: False
          use_variance_regularization_in_ad_align: False
          ad_align_beta: 1.0

