defaults:
  - negotiation_game.yaml

experiment:
  name: "negotiation_game_adv_align"
  description: "Agents trained on negotiation game with advantage alignment."
  base_seed: 344


trainers: 
  qwen_trainer:
    init_args:
      use_advantage_alignment: True
      ad_align_beta: 1.0

