defaults:
  - negotiation_game.yaml

experiment:
  name: "negotiation_game_sum_of_rewards"
  description: "Negotiation game with agents trained on sum of rewards."

trainers: 
  qwen_trainer:
    init_args:
      use_sum_credits: True

        
