defaults:
  - negotiation_game.yaml

experiment:
  name: "negotiation_game_adv_align"
  # name: "${now:%Y-%m-%d___%H-%M-%S}negotiation_game_adv_align"
  description: "Agents trained on negotiation game with advantage alignment."
  seed: 1045

training:

  qwen:
    adapters:
      sp_adapter:
        trainer_config:
          use_advantage_alignment: True
