defaults:
    - no_press_10_1_ties_naive.yaml

experiment:
    name: "no_press_10_1_ties_ad_align"

trainers:
    agent_trainer:
        class: TrainerAdAlign
        kwargs:
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_gamma: 1.0
            ad_align_exclude_k_equals_t: False
            ad_align_use_sign: False
            ad_align_beta: 1.0
            use_old_ad_align: True
            use_time_regularization: True
            use_rloo: True
            rloo_branch: False
            reuse_baseline: False
