defaults:
    - base.yaml


experiment:
    name: "tas"
    method: generate_and_train
    description: "Trust-and-Split negotiation game"
    nb_matches_per_iteration: 64


common_agent_kwargs: &common_agent_kwargs
    goal: "Maximize your total points over the whole game."
    num_message_chars: 500

agent_0_id: Alice
agent_1_id: Bob
agent_ids: ["Alice", "Bob"]

markov_games:

    simulation_class_name: TrustAndSplitSimulation
    simulation_init_args:
        agent_ids: ${agent_ids}
        rounds_per_game: 10
        quota_messages_per_agent_per_round: 1
        max_coins: 10

    agents:
        0:
            agent_id: ${agent_0_id}
            agent_class_name: TrustAndSplitAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs

        1:
            agent_id: ${agent_1_id}
            agent_class_name: TrustAndSplitAgent
            policy_id: base_llm/agent_adapter
            init_kwargs:
                <<: *common_agent_kwargs

temperature: 1.0

trainers:
    agent_trainer:
        kwargs:
            mini_batch_size: 1
