defaults:
    - tas.yaml

experiment:
    name: "tas_prev_ad_align"



trainers:
    agent_trainer:
        class: TrainerAdAlign
        kwargs:
            use_time_regularization: False
            ad_align_force_coop_first_step: False
            ad_align_clipping: null
            ad_align_gamma: 0.9
            ad_align_exclude_k_equals_t: False
            ad_align_use_sign: False
            ad_align_beta: 0.1
            ad_align_only_use_main_advantages: True
            rloo_branch: False
