defaults:
    - tas_rps_alt_naive.yaml


experiment:
    name: "tas_rps_naive"
    description: "Trust-and-Split Rock Paper Scissors negotiation game"



markov_games:
    group_by_round: True # This will merge all timesteps of a round into a single timestep
    simulation_init_args:
        alternating_hands: False


optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0

    critic_optimizer:
        module_pointer: agent_critic
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0

trainers:
    agent_trainer:
        kwargs:
            kl_coeff: 0.001
            mini_batch_size: 1
            reward_normalizing_constant: 100.0
