defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_Qwen3-8B"

models:
    base_llm:
        init_args:
            regex_max_attempts: -1
            model_name: Qwen/Qwen3-8B
            enable_thinking: false
