defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_Qwen2.5-7B-Instruct"

models:
    base_llm:
        init_args:
            regex_max_attempts: -1
            model_name: Qwen/Qwen2.5-7B-Instruct
            enable_thinking: null
