defaults:
    - tas_rps_naive.yaml
experiment:
    name: "tas_rps_naive_Meta-Llama-3.1-8B-Instruct"

models:
    base_llm:
        init_args:
            regex_max_attempts: -1
            model_name: meta-llama/Llama-3.1-8B-Instruct
            enable_thinking: null
