defaults:
    - tas_rps_no_regex.yaml

experiment:
    name: "tas_rps_no_regex_sum_of_rewards_lr3e6"

trainers:
    agent_trainer:
        class: TrainerSumRewards


optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0

    critic_optimizer:
        module_pointer: agent_critic
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0
