defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_vs_open_ai"
    nb_epochs: 300
    nb_matches_per_iteration: 32
    seed_group_size: 8
    train: true

markov_games:
    simulation_init_args:
        nb_of_rounds: 10
    agents:
        1:
            policy_id: openai_llm

optimizers:
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0


models:
    openai_llm:
        class: LargeLanguageModelOpenAI
        init_args:
            llm_id: openai_llm
            model: gpt-4.1 # https://platform.openai.com/docs/pricing
            base_url: https://api.openai.com/v1
            timeout_s: 6000.0
            regex_max_attempts: 3
            sampling_params:
                temperature: 1.0
                top_p: 1.0

train_on_which_data:
    agent_trainer: ["Alice"]
